# Copyright 2019-2024 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: 🐞 Bug Report
title: '[bug] '
description: Report a bug
labels: [ 'type: bug', 'status: needs triage' ]

body:
  - type: markdown
    attributes:
      value: |
        ## First of all
        1. Please search for [existing issues](https://github.com/Yuns-Lab/LiteView/issues?q=is%3Aissue) about this problem first.
        3. Make sure it's an issue with LiteView and not something else you are using.
        3. Remember to follow github community guidelines and be friendly.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is. Include screenshots if applicable.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A link to a reproduction repo or steps to reproduce the behaviour.
      placeholder: |
        Please provide a minimal reproduction or steps to reproduce, you may need to add files for it.
        Click textarea first, then drag or paste them into here.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        "Provide your environment, include:"
        LiteView version, MC version, File type, File (Upload it)

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear description of what you expected to happen.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.